#!/usr/bin/env ruby
# BMP to Pixeru sprite data converter (CRuby tool)
# Usage: ruby tools/bmp_to_sprite.rb input.bmp output.rb [--transparent=FF00FF]

def read_bmp(path)
  data = File.binread(path)

  sig = data[0, 2]
  raise "Not a BMP file" unless sig == "BM"

  offset = data[10, 4].unpack("V")[0]
  width = data[18, 4].unpack("V")[0]
  height = data[22, 4].unpack("V")[0]
  bpp = data[28, 2].unpack("v")[0]

  raise "Only 24-bit and 8-bit BMP supported (got #{bpp})" unless bpp == 24 || bpp == 8

  pixels = []

  if bpp == 24
    row_size = ((width * 3 + 3) / 4) * 4
    row = height - 1
    while row >= 0
      row_offset = offset + row * row_size
      col = 0
      while col < width
        idx = row_offset + col * 3
        b = data.getbyte(idx)
        g = data.getbyte(idx + 1)
        r = data.getbyte(idx + 2)
        pixels << [r, g, b]
        col += 1
      end
      row -= 1
    end
  elsif bpp == 8
    palette_offset = 54
    palette = []
    256.times do |i|
      po = palette_offset + i * 4
      b = data.getbyte(po)
      g = data.getbyte(po + 1)
      r = data.getbyte(po + 2)
      palette << [r, g, b]
    end

    row_size = ((width + 3) / 4) * 4
    row = height - 1
    while row >= 0
      row_offset = offset + row * row_size
      col = 0
      while col < width
        idx = data.getbyte(row_offset + col)
        pixels << palette[idx]
        col += 1
      end
      row -= 1
    end
  end

  { width: width, height: height, pixels: pixels }
end

def rgb_to_rgb565(r, g, b)
  ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
end

def parse_hex_colour(hex)
  hex = hex.sub(/^#/, "")
  r = hex[0, 2].to_i(16)
  g = hex[2, 2].to_i(16)
  b = hex[4, 2].to_i(16)
  [r, g, b]
end

input_path = ARGV[0]
output_path = ARGV[1]
transparent = nil

ARGV[2..].each do |arg|
  if arg.start_with?("--transparent=")
    transparent = parse_hex_colour(arg.sub("--transparent=", ""))
  end
end

unless input_path && output_path
  puts "Usage: ruby tools/bmp_to_sprite.rb input.bmp output.rb [--transparent=FF00FF]"
  exit(1)
end

bmp = read_bmp(input_path)
rgb565_data = bmp[:pixels].map do |r, g, b|
  if transparent && r == transparent[0] && g == transparent[1] && b == transparent[2]
    0x0000
  else
    rgb_to_rgb565(r, g, b)
  end
end

File.open(output_path, "w") do |f|
  f.puts "# Generated by bmp_to_sprite.rb from #{File.basename(input_path)}"
  f.puts "# Width: #{bmp[:width]}, Height: #{bmp[:height]}"
  f.puts "SPRITE_WIDTH = #{bmp[:width]}"
  f.puts "SPRITE_HEIGHT = #{bmp[:height]}"
  f.puts "SPRITE_DATA = ["

  rgb565_data.each_slice(bmp[:width]) do |row|
    f.puts "  #{row.map { |v| "0x%04X" % v }.join(", ")},"
  end

  f.puts "]"
end

puts "Converted #{input_path} (#{bmp[:width]}x#{bmp[:height]}) -> #{output_path}"
